### PR TITLE
Added sensor for energy consumtion for last month.

### PR DESCRIPTION
**Pull request by patrik3k**
The current month sensor for energy consumtion is always increasing with increasing consumtion until end of month when it resets. This adds a sensor for last month consumtion so its more. useful to compare consumtion values.

### CODE REVIEW

**Comment by sfalkman** [comment]
The changes looks good, but what happened to the PR? Why are my commits in here?
Not sure what will happen if I squash and merges this, it feels like it will be double commits i master?

**Comment by patrik3k** [comment]
Hi,
I'm so sorry. Im really truggling with GitHub and my lack off skills messed it up. I couldn't remove those double commits. I tried to wipe it clean and redo it from scratch but could get rid of it. If you think it might screw something up, skip it. I'll can try to make a new branch again and manually add the piece of code I added. 

Mvh/Regards
Patrik Ekström

**Comment by sfalkman** [comment]
No problem, I'm not that familiar either, that is why I'm unsure what this will do :)
If you create a new branch, you can probably cherry-pick your single commit to the new branch (or just copy/paste the code) and create a new PR from that. Is that OK?

**Comment by patrik3k** [comment]
This was messed up...

**Pull request closed without merging**
