### PR TITLE
Add independent update intervals for different sensor types

### PR DESCRIPTION
**Pull request by sfalkman**

### CODE REVIEW

**Comment by sfalkman** [comment]
@patrik3k could you test this branch?
Also, what do you think of the intervals for the different types?
Temp/Humidity = 5min
Power = 1min
kWh = 1h
Monthly kWh = 1h

**Comment by patrik3k** [comment]
Cant make it work, gets unknown on all sensor values. I'll dig into it more later tomorrow. Could be my Github skills that is failing me.

**Comment by patrik3k** [comment]
Hi,
I have now tried. It doesnt "compile" thats why I struggled last night. I thought it was my Corona fever... :) 
The datetime.datetime does not work after datetime was imported. 

After fixing that. It still doesnt work. This is similar to my own attemt to do this but there is something funky. I can see in the logs that the sensor APIs are called at the configured interval  BUT the sensor state inside HA is not  updated even when a new value is fetched.  The sensor state is only updated every 5 minutes the same as SCAN_INTERVAL, when lower SCAN_INTERVAL to 60 seconds the values are updated with a minimum 60 second interval. 
I dont know how this is connected but my gues is that the state engine in HA is using SCAN_INTERVAL as to update sensor states. Us scheduling calls to the async_track_time_interval is somewhat disconnected from the state engine!?!?! 

Logs and sensor values:

Sensor state is set to 1339 at 11:08 (12:08 timezone):
<template state sensor.ngenic_sensor_power=1339.7; unit_of_measurement=W, friendly_name=Ngenic sensor power, device_class=power @ 2020-03-19T11:08:20.005603+00:00>

API call gets new value different from sensor: 
2020-03-19 12:09:30 DEBUG (SyncWorker_23) [ngenicpy.models] GET tunes/ed5b71a1-7b38-ea11-a1cc-000d3ab21973/measurements/63af8148-ae46-ea11-a1cc-000d3ab21973/latest?type=power_kW with {}
2020-03-19 12:09:30 DEBUG (SyncWorker_23) [custom_components.ngenic.sensor] Updated: Ngenic sensor value=939.800000

API call gets same value but different from sensor one minute later again: 
2020-03-19 12:10:30 DEBUG (SyncWorker_2) [ngenicpy.models] GET tunes/ed5b71a1-7b38-ea11-a1cc-000d3ab21973/measurements/63af8148-ae46-ea11-a1cc-000d3ab21973/latest?type=power_kW with {}
2020-03-19 12:10:30 DEBUG (SyncWorker_2) [custom_components.ngenic.sensor] Updated: Ngenic sensor value=939.800000

Sensor state not updated:
    <template state sensor.ngenic_sensor_power=1339.7; unit_of_measurement=W, friendly_name=Ngenic sensor power, device_class=power @ 2020-03-19T11:08:20.005603+00:00>

API call gets same value different from sensor: 
2020-03-19 12:11:31 DEBUG (SyncWorker_16) [ngenicpy.models] GET tunes/ed5b71a1-7b38-ea11-a1cc-000d3ab21973/measurements/63af8148-ae46-ea11-a1cc-000d3ab21973/latest?type=power_kW with {}
2020-03-19 12:11:31 DEBUG (SyncWorker_16) [custom_components.ngenic.sensor] Updated: Ngenic sensor value=939.800000

Sensor state not updated:
    2020-03-19 11:12:24.447931+00:00
    <template state sensor.ngenic_sensor_power=1339.7; unit_of_measurement=W, friendly_name=Ngenic sensor power, device_class=power @ 2020-03-19T11:08:20.005603+00:00>

API call on the five minute mark gets same value as a few calls before but not it will set sensor: 
2020-03-19 12:13:32 DEBUG (SyncWorker_7) [ngenicpy.models] GET tunes/ed5b71a1-7b38-ea11-a1cc-000d3ab21973/measurements/63af8148-ae46-ea11-a1cc-000d3ab21973/latest?type=power_kW with {}
2020-03-19 12:13:32 DEBUG (SyncWorker_7) [custom_components.ngenic.sensor] Updated: Ngenic sensor value=919.800000

Sensor state now updated as we hit five minutes: 
    2020-03-19 11:13:21.430287+00:00
    <template state sensor.ngenic_sensor_power=919.8; unit_of_measurement=W, friendly_name=Ngenic sensor power, device_class=power @ 2020-03-19T11:13:20.005223+00:00>

**Comment by sfalkman** [comment]
You mean the `datetime.datetime` on row 44 and 61 right? Strange I didn't see any issues with that last night..

Regarding the update, you're correct in that homeassistant uses our defined `SCAN_INTERVAL` for polling. This is applied by the `should_poll` property.
Since we now have different intervals for the sensors we should probably not use polling. Looks like we can call `schedule_update_ha_state()` each time the state changes instead.

**Comment by patrik3k** [comment]
Yes 44 and 61. 
The polling mechanism is above my pay grade:) I think we can stick to every 5 minutes for all sensors unless you have skils and time to figure it out.

**Comment by sfalkman** [comment]
Pushed an update that will manually notify hass when a state have changed.
Can you test again?

**Comment by patrik3k** [comment]
Its only one out of 3 _update methods that is updated. Is that by design or do they need to be updated to the new scheduling method? 
Also why long prints and not _LOGGER.debug statements? Just asking to learn.

**Comment by sfalkman** [comment]
What do you mean only one out of 3? Each entity should fetch their current state at startup and update that to hass, after that they will update as follows:
Temp/Humidity = 5min
Power = 1min
kWh = 1h
Monthly kWh = 1h

So you should probably see a log each minute for your power (W) sensor.

Regarding the logging, yes, you should use `_LOGGER` if you're planning to keep the logging; I'm going to remove them when I'm finished :)

**Comment by patrik3k** [comment]
I might be completely off here, sorry in that case. 

The class NgenicSensor and its _update method which contains the schedule_update_ha_state to notify HA about any changes is only used by NgenicTempSensor, NgenicHumiditySensor

In NgenicPowerSensor, NgenicEnergySensor, NgenicEnergySensorMonth  the _update method is overridden and has not the schedule_update_ha_state stuff.  Dont we need to change all _update to use the new mechanism?

**Comment by sfalkman** [comment]
Oh shit you're right, that's what I get for being too cheap to buy my own Track so I can actually test this 😁

I'll make a fix tomorrow or when I get the time

**Comment by patrik3k** [comment]
Sorry, Im screwed up on the github stuff. I have cheanged some off the loggers and removed the print outs. The mechanism for different schedules works great and I added an overridden method for the actual API calls that I think look good.

**Pull request merged**
